#!/usr/bin/env bash
# Stop on any error.
set -e
# Ensure home directory is current working directory.
cd
# Download a tarball of the latest init repository.
curl -Lo init.tar.gz https://github.com/BrightFlair/init/tarball/master
# Extract the tarball to init directory.
cd init
tar -xf ../init.tar.gz
mv */* .
# Leave a file here to show it has worked:
touch ~/$1.initWorked
